[supabase]
url = "https://umqyyalyrwniobfcvohn.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtcXl5YWx5cnduaW9iZmN2b2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxNjk4NDIsImV4cCI6MjA4Mzc0NTg0Mn0.uoZDH7ZasPXFMTkZQIqB0H5AXNpUY3WL-ZVk9-khbdc"